// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mock

import (
	context "context"
	domain "frieda-golang-training-beginner/domain"

	mock "github.com/stretchr/testify/mock"
)

// IInquiryRepository is an autogenerated mock type for the IInquiryRepository type
type IInquiryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, inquiry
func (_m *IInquiryRepository) Create(ctx context.Context, inquiry *domain.Inquiry) error {
	ret := _m.Called(ctx, inquiry)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Inquiry) error); ok {
		r0 = rf(ctx, inquiry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByTransactionID provides a mock function with given fields: ctx, transactionID
func (_m *IInquiryRepository) GetByTransactionID(ctx context.Context, transactionID string) (domain.Inquiry, error) {
	ret := _m.Called(ctx, transactionID)

	var r0 domain.Inquiry
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Inquiry); ok {
		r0 = rf(ctx, transactionID)
	} else {
		r0 = ret.Get(0).(domain.Inquiry)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
