// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mock

import (
	context "context"
	domain "frieda-golang-training-beginner/domain"

	mock "github.com/stretchr/testify/mock"
)

// IInquiryUsecase is an autogenerated mock type for the IInquiryUsecase type
type IInquiryUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *IInquiryUsecase) Create(ctx context.Context, request domain.CreateInquiryRequestPayload) (domain.Inquiry, error) {
	ret := _m.Called(ctx, request)

	var r0 domain.Inquiry
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateInquiryRequestPayload) domain.Inquiry); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(domain.Inquiry)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateInquiryRequestPayload) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
