// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import (
	context "context"
	domain "frieda-golang-training-beginner/domain"

	mock "github.com/stretchr/testify/mock"
)

// IPaymentCodeRepository is an autogenerated mock type for the IPaymentCodeRepository type
type IPaymentCodeRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, paymentCode
func (_m *IPaymentCodeRepository) Create(ctx context.Context, paymentCode *domain.PaymentCode) error {
	ret := _m.Called(ctx, paymentCode)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PaymentCode) error); ok {
		r0 = rf(ctx, paymentCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, uuid
func (_m *IPaymentCodeRepository) GetByID(ctx context.Context, uuid string) (domain.PaymentCode, error) {
	ret := _m.Called(ctx, uuid)

	var r0 domain.PaymentCode
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.PaymentCode); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(domain.PaymentCode)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
