// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mock

import (
	context "context"
	domain "frieda-golang-training-beginner/domain"

	mock "github.com/stretchr/testify/mock"
)

// IPaymentUsecase is an autogenerated mock type for the IPaymentUsecase type
type IPaymentUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *IPaymentUsecase) Create(ctx context.Context, request domain.CreatePaymentRequestPayload) (domain.Payment, error) {
	ret := _m.Called(ctx, request)

	var r0 domain.Payment
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreatePaymentRequestPayload) domain.Payment); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(domain.Payment)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.CreatePaymentRequestPayload) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
